const segments = [
  { name: "Gran Empresa" },
  { name: "Corporativo" },
  { name: "Otros" },
  { name: "Empresa" },
];
const colores = [
  {
    FieldValueId: 56,
    Value: "Almendra",
    IsActive: false,
    Position: 1,
  },
  {
    FieldValueId: 57,
    Value: "Aluminio",
    IsActive: false,
    Position: 2,
  },
  {
    FieldValueId: 58,
    Value: "Amarillo",
    IsActive: false,
    Position: 3,
  },
  {
    FieldValueId: 59,
    Value: "Aqua",
    IsActive: false,
    Position: 4,
  },
  {
    FieldValueId: 60,
    Value: "Arena",
    IsActive: false,
    Position: 5,
  },
  {
    FieldValueId: 61,
    Value: "Azul",
    IsActive: false,
    Position: 6,
  },
  {
    FieldValueId: 62,
    Value: "Beige",
    IsActive: false,
    Position: 7,
  },
  {
    FieldValueId: 63,
    Value: "Blanco",
    IsActive: false,
    Position: 8,
  },
  {
    FieldValueId: 64,
    Value: "Bronce",
    IsActive: false,
    Position: 9,
  },
  {
    FieldValueId: 65,
    Value: "Café",
    IsActive: false,
    Position: 10,
  },
  {
    FieldValueId: 66,
    Value: "Calipso",
    IsActive: false,
    Position: 11,
  },
  {
    FieldValueId: 67,
    Value: "Camel",
    IsActive: false,
    Position: 12,
  },
  {
    FieldValueId: 68,
    Value: "Celeste",
    IsActive: false,
    Position: 13,
  },
  {
    FieldValueId: 69,
    Value: "Champaña",
    IsActive: false,
    Position: 14,
  },
  {
    FieldValueId: 70,
    Value: "Chocolate",
    IsActive: false,
    Position: 15,
  },
  {
    FieldValueId: 71,
    Value: "Cobre",
    IsActive: false,
    Position: 16,
  },
  {
    FieldValueId: 72,
    Value: "Crema",
    IsActive: false,
    Position: 17,
  },
  {
    FieldValueId: 73,
    Value: "Crudo",
    IsActive: false,
    Position: 18,
  },
  {
    FieldValueId: 74,
    Value: "Dorado",
    IsActive: false,
    Position: 19,
  },
  {
    FieldValueId: 75,
    Value: "Fucsia",
    IsActive: false,
    Position: 20,
  },
  {
    FieldValueId: 76,
    Value: "Grafito",
    IsActive: false,
    Position: 21,
  },
  {
    FieldValueId: 77,
    Value: "Gris",
    IsActive: false,
    Position: 22,
  },
  {
    FieldValueId: 78,
    Value: "Gris oscuro",
    IsActive: false,
    Position: 23,
  },
  {
    FieldValueId: 79,
    Value: "Guinda",
    IsActive: false,
    Position: 24,
  },
  {
    FieldValueId: 80,
    Value: "Habano",
    IsActive: false,
    Position: 25,
  },
  {
    FieldValueId: 81,
    Value: "Lila",
    IsActive: false,
    Position: 26,
  },
  {
    FieldValueId: 82,
    Value: "Marfil",
    IsActive: false,
    Position: 27,
  },
  {
    FieldValueId: 83,
    Value: "Multicolor",
    IsActive: false,
    Position: 28,
  },
  {
    FieldValueId: 84,
    Value: "Naranjo",
    IsActive: false,
    Position: 29,
  },
  {
    FieldValueId: 85,
    Value: "Natural",
    IsActive: false,
    Position: 30,
  },
  {
    FieldValueId: 86,
    Value: "Negro",
    IsActive: false,
    Position: 31,
  },
  {
    FieldValueId: 87,
    Value: "Neutro",
    IsActive: false,
    Position: 32,
  },
  {
    FieldValueId: 88,
    Value: "Oro",
    IsActive: false,
    Position: 33,
  },
  {
    FieldValueId: 89,
    Value: "Perla",
    IsActive: false,
    Position: 34,
  },
  {
    FieldValueId: 90,
    Value: "Plata",
    IsActive: false,
    Position: 35,
  },
  {
    FieldValueId: 91,
    Value: "Rojo",
    IsActive: false,
    Position: 36,
  },
  {
    FieldValueId: 92,
    Value: "Rosa",
    IsActive: false,
    Position: 37,
  },
  {
    FieldValueId: 93,
    Value: "Tabaco",
    IsActive: false,
    Position: 38,
  },
  {
    FieldValueId: 94,
    Value: "Taupé",
    IsActive: false,
    Position: 39,
  },
  {
    FieldValueId: 95,
    Value: "Terracota",
    IsActive: false,
    Position: 40,
  },
  {
    FieldValueId: 96,
    Value: "Transparente",
    IsActive: false,
    Position: 41,
  },
  {
    FieldValueId: 97,
    Value: "Turquesa",
    IsActive: false,
    Position: 42,
  },
  {
    FieldValueId: 98,
    Value: "Verde",
    IsActive: false,
    Position: 43,
  },
  {
    FieldValueId: 99,
    Value: "Violeta",
    IsActive: false,
    Position: 44,
  },
];

const tallas = [
  {
    FieldValueId: 100,
    Value: "34",
    IsActive: true,
    Position: 1,
  },
  {
    FieldValueId: 101,
    Value: "35",
    IsActive: true,
    Position: 2,
  },
  {
    FieldValueId: 102,
    Value: "36",
    IsActive: true,
    Position: 3,
  },
  {
    FieldValueId: 103,
    Value: "37",
    IsActive: true,
    Position: 4,
  },
  {
    FieldValueId: 104,
    Value: "38",
    IsActive: true,
    Position: 5,
  },
  {
    FieldValueId: 105,
    Value: "39",
    IsActive: true,
    Position: 6,
  },
  {
    FieldValueId: 106,
    Value: "40",
    IsActive: true,
    Position: 7,
  },
  {
    FieldValueId: 107,
    Value: "41",
    IsActive: true,
    Position: 8,
  },
  {
    FieldValueId: 108,
    Value: "42",
    IsActive: true,
    Position: 9,
  },
  {
    FieldValueId: 109,
    Value: "43",
    IsActive: true,
    Position: 10,
  },
  {
    FieldValueId: 110,
    Value: "44",
    IsActive: true,
    Position: 11,
  },
  {
    FieldValueId: 111,
    Value: "45",
    IsActive: true,
    Position: 12,
  },
  {
    FieldValueId: 112,
    Value: "46",
    IsActive: true,
    Position: 13,
  },
  {
    FieldValueId: 113,
    Value: "L",
    IsActive: true,
    Position: 16,
  },
  {
    FieldValueId: 114,
    Value: "M",
    IsActive: true,
    Position: 15,
  },
  {
    FieldValueId: 115,
    Value: "S",
    IsActive: true,
    Position: 14,
  },
  {
    FieldValueId: 116,
    Value: "XL",
    IsActive: true,
    Position: 17,
  },
  {
    FieldValueId: 117,
    Value: "XXL",
    IsActive: true,
    Position: 18,
  },
  {
    FieldValueId: 420,
    Value: "39.5",
    IsActive: true,
    Position: 19,
  },
  {
    FieldValueId: 421,
    Value: "40.5",
    IsActive: true,
    Position: 20,
  },
  {
    FieldValueId: 422,
    Value: "41.5",
    IsActive: true,
    Position: 21,
  },
  {
    FieldValueId: 423,
    Value: "42.5",
    IsActive: true,
    Position: 22,
  },
  {
    FieldValueId: 424,
    Value: "43.5",
    IsActive: true,
    Position: 23,
  },
  {
    FieldValueId: 425,
    Value: "35.5",
    IsActive: true,
    Position: 24,
  },
  {
    FieldValueId: 426,
    Value: "36.5",
    IsActive: true,
    Position: 25,
  },
  {
    FieldValueId: 427,
    Value: "37.5",
    IsActive: true,
    Position: 26,
  },
  {
    FieldValueId: 428,
    Value: "38.5",
    IsActive: true,
    Position: 27,
  },
  {
    FieldValueId: 429,
    Value: "47",
    IsActive: true,
    Position: 28,
  },
  {
    FieldValueId: 430,
    Value: "47.5",
    IsActive: true,
    Position: 29,
  },
];

const variedades = [
  {
    FieldValueId: 144,
    Value: "Aqua",
    IsActive: true,
    Position: 1,
  },
  {
    FieldValueId: 145,
    Value: "Bebé",
    IsActive: true,
    Position: 2,
  },
  {
    FieldValueId: 146,
    Value: "Black",
    IsActive: true,
    Position: 3,
  },
  {
    FieldValueId: 147,
    Value: "Café",
    IsActive: true,
    Position: 4,
  },
  {
    FieldValueId: 148,
    Value: "Canela",
    IsActive: true,
    Position: 5,
  },
  {
    FieldValueId: 149,
    Value: "Cereza",
    IsActive: true,
    Position: 6,
  },
  {
    FieldValueId: 150,
    Value: "Chicle",
    IsActive: true,
    Position: 7,
  },
  {
    FieldValueId: 151,
    Value: "Chirimoya",
    IsActive: true,
    Position: 8,
  },
  {
    FieldValueId: 152,
    Value: "Citrus",
    IsActive: true,
    Position: 9,
  },
  {
    FieldValueId: 153,
    Value: "Coco",
    IsActive: true,
    Position: 10,
  },
  {
    FieldValueId: 154,
    Value: "Frambuesa",
    IsActive: true,
    Position: 11,
  },
  {
    FieldValueId: 155,
    Value: "Fresh",
    IsActive: true,
    Position: 12,
  },
  {
    FieldValueId: 156,
    Value: "Frutilla",
    IsActive: true,
    Position: 13,
  },
  {
    FieldValueId: 157,
    Value: "Guínda",
    IsActive: true,
    Position: 14,
  },
  {
    FieldValueId: 158,
    Value: "Lavanda",
    IsActive: true,
    Position: 15,
  },
  {
    FieldValueId: 159,
    Value: "Limón",
    IsActive: true,
    Position: 16,
  },
  {
    FieldValueId: 160,
    Value: "Mango",
    IsActive: true,
    Position: 17,
  },
  {
    FieldValueId: 161,
    Value: "Manzana",
    IsActive: true,
    Position: 18,
  },
  {
    FieldValueId: 162,
    Value: "Maracuyá",
    IsActive: true,
    Position: 19,
  },
  {
    FieldValueId: 163,
    Value: "Mora",
    IsActive: true,
    Position: 20,
  },
  {
    FieldValueId: 164,
    Value: "Naranja",
    IsActive: true,
    Position: 21,
  },
  {
    FieldValueId: 165,
    Value: "New Car",
    IsActive: true,
    Position: 22,
  },
  {
    FieldValueId: 166,
    Value: "Passion",
    IsActive: true,
    Position: 23,
  },
  {
    FieldValueId: 167,
    Value: "Sandía",
    IsActive: true,
    Position: 24,
  },
  {
    FieldValueId: 168,
    Value: "Tropical",
    IsActive: true,
    Position: 25,
  },
  {
    FieldValueId: 169,
    Value: "Vainilla",
    IsActive: true,
    Position: 26,
  },
  {
    FieldValueId: 412,
    Value: "Flores",
    IsActive: true,
    Position: 27,
  },
  {
    FieldValueId: 413,
    Value: "Té verde",
    IsActive: true,
    Position: 28,
  },
  {
    FieldValueId: 414,
    Value: "Eucaliptus",
    IsActive: true,
    Position: 29,
  },
  {
    FieldValueId: 415,
    Value: "Fruta",
    IsActive: true,
    Position: 30,
  },
  {
    FieldValueId: 416,
    Value: "Primavera",
    IsActive: true,
    Position: 31,
  },
  {
    FieldValueId: 417,
    Value: "Menta",
    IsActive: true,
    Position: 32,
  },
  {
    FieldValueId: 418,
    Value: "Derecha",
    IsActive: true,
    Position: 33,
  },
  {
    FieldValueId: 419,
    Value: "Izquierda",
    IsActive: true,
    Position: 34,
  },
  {
    FieldValueId: 432,
    Value: "Brisa Marina",
    IsActive: true,
    Position: 35,
  },
  {
    FieldValueId: 437,
    Value: "Macho",
    IsActive: true,
    Position: 36,
  },
  {
    FieldValueId: 438,
    Value: "Hembra",
    IsActive: true,
    Position: 37,
  },
  {
    FieldValueId: 732,
    Value: "Cedro",
    IsActive: true,
    Position: 38,
  },
  {
    FieldValueId: 733,
    Value: "Miel",
    IsActive: true,
    Position: 39,
  },
];

module.exports = {
  segments,
  colores,
  tallas,
  variedades,
};
